### ISSUE TITLE
Enter and spacebar to open/close accordion item

### ISSUE THREAD

**Issue by robertvrabel** [Alhadis/Accordion#11] opened 2018-05-10 17:08 UTC
First, thanks for the great package!

So I'm seeing code for

```js
/** Enter: Toggle */
case 13: {
    THIS.open = !THIS.open;
    break;
}
```

But this doesn't appear to be working, it does not toggle the item to be open and closed. Ideally i'd also like to have the spacebar do the same thing. The right and left arrows work as I'd expect though.

Is this behavior something that could be added? Or do you have a recommendation of adding my own event listener to accomplish this?

**Comment by Alhadis** [comment] 2018-05-14 07:59
:wave: Hey @robertvrabel,

You're right about the space-bar: I'll make a note of adding it. For the <kbd>Enter</kbd> key, however, you *should* be able to toggle the folds when they receive focus. Can you confirm that the event is firing? Add this somewhere in the page, then press <kbd>Enter</kbd>:

~~~js
window.addEventListener("keydown", function(event){
	if(event.keyCode === 13)
		console.log("ENTER key pressed. This should be working...");
	else
		console.log("Wrong keycode! It should be " + event.keyCode);
});
~~~

If you see the first message, it's possible that something on the page is intercepting the `keydown` event and stopping it from propagating (which means it doesn't reach the `Accordion` instance...)

**Comment by robertvrabel** [comment] 2018-05-14 12:51
@Alhadis Thanks for the response! So I did debug the code directly and I've confirmed it does get into this when I hit enter on the element. This reports `true`, but does not actually open the fold. I'm not exactly where to debug it from there but if you can point in the right direction I can keep following the code to see where its not triggering the open.

```js
/** Enter: Toggle */
case 13: {
    console.log(!THIS.open);
    THIS.open = !THIS.open;
    break;
}
```

**Comment by Alhadis** [comment] 2018-05-14 13:06
Could you add `console.trace(THIS);` and copy+paste the resulting stack trace, please? Also, what browser/device are you witnessing this on? Is it consistent across all platforms, or something specific?

This is quite strange, and so far I'm out of theories as to why this could be happening. 🤔

**Comment by robertvrabel** [comment] 2018-05-14 14:00
So I copied the HTML example into my page that you provide and it works. So its totally on me because I wrapped the "heading" in html link (for accessibility reasons because i'm interested in deep-linking to open one eventually). So it looks like if I add this, it works properly:

```js
/** Enter: Toggle */
case 13: {
    THIS.open = !THIS.open;
	
    if(heading.tagName === 'A') {
        heading.click();
    }

    break;
}
```

I'm not sure if this is optimal. So my question would be 1) Is there an easy way for me to add this outside the package? Or 2) Would you accept a pull request to support links as headings?

**Comment by Alhadis** [comment] 2018-05-14 14:04
Okay, whoa, wait a second. You'll need to show me the actual DOM outline for the Accordion markup. This will probably explain everything – you can blank any body text that can't be shown for NDA reasons.

**Comment by robertvrabel** [comment] 2018-05-14 14:11
Yes, sorry I didn't mention that at first I realize thats a big part of it :). It just worked out of the box and I noticed you were referencing the heading as `firstElement` so I thought it was good to go. Coming from anther accordion package that relied on JavaScript, we're trying to stick to the same HTML so this is what i'm using. I was able to style it to look like this:

<img width="904" alt="Screen-shot 2018-05-14 at 10:08:59 am" src="https://user-images.githubusercontent.com/634788/40002504-faa645d8-575e-11e8-8152-c766ed2e3a23.png">

```html
<ul class="accordion">
    <li>
        <a href="#panel1a">Accordion 1</a>
        <div id="panel1a" class="fold">
            <p>Panel 1. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
    </li>
    <li>
        <a href="#panel2a">Accordion 2</a>
        <div id="panel2a" class="fold">
            <p>Panel 2. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
    </li>
    <li>
        <a href="#panel3a">Accordion 3</a>
        <div id="panel3a"  class="fold">
            <p>Panel 3. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
    </li>
</ul>
```

**Comment by robertvrabel** [comment] 2018-05-14 14:13
I actually have some code that automatically applies the `class="fold"` on it as well. We try really hard to keep our markup simple because people use it in a wysiwyg editor. So we just rely on that structure and one `class="accordion"` to accomplish it.

```js
document.querySelectorAll('ul.accordion > li').forEach(function(item) {
    // Make the items absolute positioning now that we know javascript is enabled
    item.classList.add('absolute')

    // Apply the content fold
    item.querySelector('div').classList.add('fold');
});
```

**Comment by Alhadis** [comment] 2018-05-14 14:50
Alright, we're getting there. I'm able to reproduce what's happening by replacing the accordion in `demos/anim-switch.htm` with the HTML snippet you've given above. Could you also share the CSS you're using? CSS is pivotal to the accordion's functionality (as it should be for any front-end component, IMHO).

Just curious, is there any particular reason you need the headings to link to their fold element (via use of `#panel2a` and `panel2a`)?

**EDIT:** Apologies for making all those minor edits to your posts, I can't stand seeing unhighlighted code blocks in markdown. 😁It makes my teeth itch.

**Comment by Alhadis** [comment] 2018-05-14 14:57
Oh! Wait, of course there's a particular reason you need headings to link to stuff... you need permalinks/deep-linking to be possible. Which, I admit, is *definitely* an important addition. 😅 Surprised I didn't think of that...

**Comment by robertvrabel** [comment] 2018-05-14 15:08
Yea here is the output, i'll provide CSS and SASS:

CSS:

```css
.accordion {
  padding: 0;
  margin-bottom: 1rem;
  position: relative;
  list-style: none;
  background: #efefef;
}

.accordion > li {
  width: 100%;
  position: absolute;
}

.accordion > li > a {
  cursor: pointer;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  position: relative;
  display: block;
  padding: 1.25rem 1rem;
  border: 1px solid #d5d5d5;
  border-bottom: 0;
  line-height: 1;
  color: foreground(#efefef, #0c5449);
  text-decoration: none;
  font-weight: bold;
}

.accordion > li > a:first-child:hover,
.accordion > li > a:first-child:focus {
  background-color: #e6e6e6;
}

.accordion > li > a::before {
  position: absolute;
  top: 50%;
  right: 1rem;
  margin-top: -0.5rem;
  content: '+';
}

.accordion > li.open > a::before {
  content: '\2013';
}

.accordion > li > .fold {
  padding: 1rem;
  border: 1px solid #d5d5d5;
  border-top: none;
  background-color: #fff;
  color: foreground(#efefef, #0c5449);
}

.accordion > * {
  overflow: hidden;
  padding: 0;
  margin: 0;
  -webkit-transition: .3s ease all;
  transition: .3s ease all;
}
```

SCSS:

```css
.accordion {
    padding: 0;
    margin-bottom: 1rem;
    position: relative;
    list-style: none;
    background: #efefef;

    & > li {
        width: 100%;
        position: absolute;

        > a {
            cursor: pointer;
            user-select: none;
            position: relative;
            display: block;
            padding: 1.25rem 1rem;
            border: 1px solid #d5d5d5;
            border-bottom: 0;
            line-height: 1;
            color: foreground(#efefef, #0c5449);
            text-decoration: none;
            font-weight: bold;

            &:first-child:hover,
            &:first-child:focus, {
                background-color: #e6e6e6;
            }

            // Open symbol
            &::before {
                position: absolute;
                top: 50%;
                right: 1rem;
                margin-top: -0.5rem;
                content: '+';
            }
        }

        // Close symbol
        &.open > a::before {
            content: '\2013';
        }

        // Content area
        > .fold {
            padding: 1rem;
            border: 1px solid #d5d5d5;
            border-top: none;
            background-color: #fff;
            color: foreground(#efefef, #0c5449);
        }
    }

    > * {
        overflow: hidden;
        padding: 0;
        margin: 0;
        transition: 0.3s ease all;
    }
}
```

**Comment by robertvrabel** [comment] 2018-05-14 15:15
Yea I haven't looked into deep linking yet but wanted to make sure the markup at least accounts for it as a possibility. Another thing we do is make sure it works without javascript so none of the content is hidden. So we actually apply the `li { position: absolute }` with javascript, so that way it turns it from:

<img width="926" alt="screen shot 2018-05-14 at 11 10 48 am" src="https://user-images.githubusercontent.com/634788/40006232-dac9ac74-5767-11e8-8cb7-9937f4381b44.png">

to this with javascript turned off (or javascript is broken for whatever reason):

<img width="932" alt="screen shot 2018-05-14 at 11 11 18 am" src="https://user-images.githubusercontent.com/634788/40006268-f3745026-5767-11e8-8094-450c45f70e4c.png">

Could be styled better but viewable, clickable, and anchorable still :)

**Comment by Alhadis** [comment] 2018-05-14 15:40
Ah, I understand! Good man, you're considering accessibility. 😉 I like seeing that.

You could simplify that by setting the `enabledClass` option to `"enabled"` (at the moment, it's using `"accordion"`, which is also what's applying cosmetic styling to the content). Then make a few tweaks in the CSS so the positioning rulesets use `.enabled.accordion` in their selectors instead:

~~~diff
diff --git a/src/accordion.css b/src/accordion.css
index 97236e6..2e59995 100644
--- a/src/accordion.css
+++ b/src/accordion.css
@@ -1,11 +1,11 @@
 /** Core styling */
-.accordion{
+.accordion.enabled{
 	padding: 0;
 	margin:  0;
 	position: relative;
 	list-style: none;
 }
-	.accordion > *{
+	.accordion.enabled > *{
 		position: absolute;
 		overflow: hidden;
 		padding: 0;
~~~

**Comment by robertvrabel** [comment] 2018-05-14 15:55
I work at a University so we're big on accessibility 👍 

Nice! I like that idea, i will try it out. Thanks for working with me on this, i think it'll be benefit everyone the more accessible we can make the package :)

**Comment by Alhadis** [comment] 2018-05-14 16:31
> i think it'll be benefit everyone the more accessible we can make the package :)

Haha, your timing is perfect, mate. 😀I recently started studying WAI-ARIA specifications in greater depth, and noticed the `role` attributes I assign each `Fold` object mightn't be correct. Guess I'll need the opinion of an ARIA-expert to give their `aria-*` and `role` attribute suggestions... 😞

Chrome recently made accessibility trees visible to webdevs with a new tab in the DevTools. Here it lists ARIA properties assigned through-this page...

<img src="https://user-images.githubusercontent.com/2346707/40010059-0757f348-57e7-11e8-8859-3e1e205337c3.png" width="560" />

Don't forget about it: WAI-ARIA is important for making content accessible.

**Comment by robertvrabel** [comment] 2018-05-17 12:23
@Alhadis Is there anything you'd like for me to contribute? i don't mind putting together a PR but I don't want to infringe if you have something in the works :)

**Comment by Alhadis** [comment] 2018-05-17 12:26
I have three commits published locally, one of which will close this since it contains `fixes #11`:

~~~
commit f0893e3fdc5d8c405106ac4e7c1a534e6cd11231 (HEAD -> master)
Author: Alhadis <gardnerjohng@gmail.com>
Date:   Tue May 15 17:57:39 2018 +1000

    Toggle focussed folds when pressing spacebar
    
    Partially fixes #11.
~~~

I fell asleep and crashed while fixing the rest, sorry. 😀

**Comment by Alhadis** [comment] 2018-05-17 15:49
Should the `#fragment` part at the end of the URL bar update each time an accordion's fold is closed or opened?

It would certainly make for easier sharing... 🤔

**Comment by robertvrabel** [comment] 2018-05-17 16:27
Yes! That would be a great feature!

**Comment by Alhadis** [comment] 2018-05-17 16:28
Will do, then. ;-)

**Closed as completed** 2018-05-17 17:29 UTC

**Comment by Alhadis** [comment] 2018-05-18 01:34
Erh, actually... won't do, sorry @robertvrabel. 😞I realised this is feature-creep: front-end routing should be implemented using a dedicated router component (which would make use of an Accordion's `onToggle` callback for URL changes).

**Comment by robertvrabel** [comment] 2018-05-18 11:32
@Alhadis Ok bummer. What about the spacebar and enter with an A tag though? Will that make it into a release?

**Comment by Alhadis** [comment] 2018-05-18 11:35
That's already fixed. 😉 It'll be cut in a release once I've finished adding support for a `modal` option (which automatically closes the current fold when another is selected…)

You can try it now for yourself by checking out `master` locally and poking around [`demos/heading-links.htm`](https://github.com/Alhadis/Accordion/blob/master/demos/heading-links.htm).
